version: '3'

services:
  db_ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    depends_on:
      - "db"
    environment:
      database_client: mysql
      database__connection__database: db_ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ximira
  
  volume: ./my-app:/var/lib/ghost/content

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${database__connection__password}

